chiki/base/__init__.py
# coding: utf-8
from flask import Blueprint, current_app
from flask.ext.login import LoginManager
from ..mongoengine import MongoEngine
from flask.ext.cache import Cache

db = MongoEngine()
login = LoginManager()
cache = Cache()
page = Blueprint('page', __name__)


class Base(object):

    @classmethod
    def init(cls, app, key=None):
        key = key or cls.__name__.upper()
        if key in app.config:
            return cls(app, key)

    def __init__(self, app=None, key=None, config=None, holder=None,
                 name=None):
        self.name = name or self.__class__.__name__.lower()
        self.key = key
        self.config = config
        self.holder = holder
        if app:
            self.init_app(app)

    def init_app(self, app):
        self.app = app

        name = self.__class__.__name__
        if self.config is None:
            self.config = app.config.get(self.key or name.upper())

        self.puppets = dict()
        for key, config in self.config.get('puppets', dict()).iteritems():
            self.puppets[key] = self.__class__(
                app=app, key=key, config=config, holder=self)

        if not hasattr(app, name.lower()) and not self.holder:
            setattr(app, name.lower(), self)

    def get_key(self):
        return self.key if self.holder else 'default'

    def get_config(self, key, default=None, repalce=True, config=None):
        if config and key in config:
            return config.get(key)

        if self.holder:
            value = self.config.get(
                key, self.holder.get_config(key, default, False))
        else:
            value = self.config.get(key, default)

        if repalce and isinstance(value, (str, unicode)):
            return value.replace('[key]', self.get_key())
        return value

    def get_puppet(self, key):
        if self.holder:
            return self.holder.get_puppet(key)
        return self if key in ['default', ''] else self.puppets.get(key)

    @property
    def item(self):
        item = self.get_config('item', dict())
        Item = current_app.cool_manager.models.get('Item')
        return Item.choice(item.get('key'), item.get('value', 'default'),
                           item.get('name', ''))
    @property
    def puppet(self):
        return self.get_puppet(self.item)

chiki/contrib/users/__init__.py
# coding: utf-8
from chiki.base import db
from chiki.contrib.common import Channel
from chiki.contrib.users import admin, apis, forms, funcs, models, oauth, views
from chiki.contrib.users.base import user_manager
from chiki.contrib.users.oauth import wxauth_required
from chiki.utils import AttrDict, is_ajax, sign
from chiki.verify import init_verify
from flask import request, flash, current_app, redirect, abort as _abort
from flask.ext.login import LoginManager, current_user, login_url, decode_cookie
from chiki.api.const import abort, LOGIN_REQUIRED

__all__ = [
    'BaseManager', 'user_manager', 'um', 'UserManager', 'wxauth_required',
]


class BaseManager(object):
    def __init__(self, name='', url_prefix=''):
        self.name = name
        self.url_prefix = url_prefix
        self.managers = AttrDict()
        self.apis = AttrDict()
        self.models = AttrDict()
        self.forms = AttrDict()
        self.funcs = AttrDict()
        self.config = AttrDict()
        self.tpls = AttrDict()

    def get(self, key):
        if key not in self.managers:
            self.managers[key] = BaseManager(key, url_prefix='/%s' % key)
        return self.managers.get(key)

    def add_model(self, model, name=None):
        self.models[name or model.__name__] = model
        return model

    def add_form(self, form, name=None):
        self.forms[name or form.__name__] = form
        return form

    def add_func(self, func, name=None):
        self.funcs[name or func.__name__] = func
        return func

    def add_api(self, *args, **kwargs):
        def wrapper(cls):
            self.apis[cls.__name__] = (cls, args, kwargs)
            return cls
        return wrapper

    def init_apis(self, api):
        for cls, args, kwargs in self.apis.itervalues():
            _web = kwargs.pop('_web', False)
            _api = kwargs.pop('_api', True)
            if _api is True:
                if self.url_prefix:
                    args = list(args)
                    args[0] = self.url_prefix + args[0]
                if self.name:
                    kwargs.setdefault('endpoint', '%s_%s' % (
                        self.name, cls.__name__.lower))
                api.add_resource(cls, *args, **kwargs)
            kwargs['_web'] = _web
            kwargs['_api'] = _api

        for manager in self.managers.itervalues():
            manager.init_apis(api)

    def init_wapis(self, api):
        for cls, args, kwargs in self.apis.itervalues():
            _web = kwargs.pop('_web', False)
            _api = kwargs.pop('_api', True)
            if _web is True:
                if self.url_prefix:
                    args = list(args)
                    args[0] = self.url_prefix + args[0]
                if self.name:
                    kwargs.setdefault('endpoint', '%s_%s' % (
                        self.name, cls.__name__.lower))
                api.add_resource(cls, *args, **kwargs)
            kwargs['_web'] = _web
            kwargs['_api'] = _api

        for manager in self.managers.itervalues():
            manager.init_wapis(api)


class UserManager(BaseManager):

    def __init__(self, app=None):
        super(UserManager, self).__init__()
        self.init_models()
        self.init_forms()
        self.init_funcs()
        self.init_tpls()
        if app:
            self.init_app(app)

    def init_app(self, app):
        self.app = app
        app.user_manager = self
        self.init_login()
        self.init_config()
        self.init_resources()
        self.init_oauth()
        self.init_jinja()
        init_verify(app)

    def init_login(self):
        self.login = LoginManager(self.app)
        self.login.login_view = 'users.login' if self.app.is_web else '/users/login'

        @self.login.user_loader
        def load_user(id):
            id = str(id)
            if id.startswith('wechat:'):
                return um.models.WeChatUser.objects(id=id.split(':')[-1]).first()
            elif id.startswith('qq:'):
                return um.models.QQUser.objects(id=id.split(':')[-1]).first()
            elif id.startswith('weibo:'):
                return um.models.WeiBoUser.objects(id=id.split(':')[-1]).first()
            elif id.startswith('channel:'):
                return Channel.objects(id=int(id.split(':')[-1])).first()

            try:
                uid, s = id.rsplit(u'|', 1)
                user = um.models.User.objects(id=int(uid)).first()
                if user:
                    key = current_app.config.get('SECRET_KEY')
                    if s == sign(key, password=user.password):
                        return user
            except:
                pass

        @self.login.header_loader
        def header_callback(header):
            return load_user(decode_cookie(header))

        # login = self.login
        # @login.unauthorized_handler
        # def unauthorized():
        #     if is_ajax():
        #         abort(LOGIN_REQUIRED)

        #     if not login.login_view:
        #         _abort(401)

        #     if login.login_message:
        #         if login.localize_callback is not None:
        #             flash(login.localize_callback(login.login_message),
        #                   category=login.login_message_category)
        #         else:
        #             flash(login.login_message,
        #                   category=login.login_message_category)

        #     return redirect(login_url(login.login_view, request.url))

    @property
    def need_email(self):
        return self.allow_email and current_user.is_authenticated() \
            and (not current_user.is_user() or not current_user.email)

    @property
    def need_phone(self):
        return self.allow_phone and current_user.is_authenticated() \
            and (not current_user.is_user() or not current_user.phone)

    def init_config(self):
        config = self.app.config.get('CHIKI_USER', {})
        self.allow_email = self.config.allow_email = config.get('allow_email', False)
        self.allow_phone = self.config.allow_phone = config.get('allow_phone', True)
        self.config.allow_redirect = config.get('allow_redirect', True)
        self.config.userinfo = config.get('userinfo', True)
        self.config.auto_heart = config.get('auto_heart', True)
        self.config.auto_wxauth = config.get('auto_wxauth', True)
        self.config.register_auto_login = config.get('register_auto_login', True)
        self.config.reset_password_auto_login = config.get('reset_password_auto_login', True)
        self.config.required_bind_password = config.get('required_bind_password', True)
        self.config.include_apis = config.get('include_apis', {})
        self.config.exclude_apis = config.get('exclude_apis', {})
        self.config.allow_oauth_urls = config.get('allow_oauth_urls',
            ['users.logout', 'users.bind', 'bindphone', 'bindemail', 'bindauto',
                'sendemailcode', 'authemailcode', 'sendphonecode', 'authphonecode',
                'verify_code', 'uploads'])
        self.config.oauth_model = config.get('oauth_model', 'select')
        self.config.oauth_remember = config.get('oauth_remeber', True)
        self.config.oauth_auto_update = config.get('oauth_auto_update', False)
        self.config.bind_url = config.get('bind_url', '/users/bind.html')
        self.config.login_next = config.get('login_next', '/')

    def init_models(self):
        for key in models.__all__:
            if key not in self.models:
                self.models[key] = getattr(models, key)

    def init_forms(self):
        for key in forms.__all__:
            if key not in self.forms:
                self.forms[key] = getattr(forms, key)

    def init_funcs(self):
        for module in [apis, funcs, oauth]:
            for key in module.__all__:
                if key not in self.funcs:
                    func = getattr(module, key)
                    if callable(func):
                        self.funcs[key] = func

    def init_tpls(self):
        self.tpls.login = 'users/login.html'
        self.tpls.register = 'users/register.html'
        self.tpls.register_email = 'users/register_email.html'
        self.tpls.reset_password = 'users/reset_password.html'
        self.tpls.reset_password_email = 'users/reset_password_email.html'
        self.tpls.bind = 'users/bind.html'

    def init_resources(self):
        for key in apis.resources:
            if key not in self.apis \
                    and key not in self.config.exclude_apis \
                    and (not self.config.include_apis or key in self.config.include_apis):
                self.apis[key] = apis.resources.get(key)

    def init_oauth(self):
        self.funcs.init_oauth(self.app)

    def init_jinja(self):
        self.app.context_processor(self.context_processor)

    def context_processor(self):
        return dict(um=self)

    def init_web(self):
        self.app.register_blueprint(views.bp, url_prefix='/users')


um = UserManager()

chiki/contrib/users/views.py
# coding: utf-8
from chiki.utils import json_error
from chiki.web import error
from chiki.contrib.users.base import user_manager as um
from flask import Blueprint, request, render_template, redirect
from flask import url_for, current_app
from flask.ext.login import current_user, login_user, logout_user, login_required

bp = Blueprint('users', __name__)


@bp.route('/register.html')
def register():
    next = request.args.get('next', url_for('users.login'))
    if current_user.is_authenticated():
        return redirect(next)

    if current_app.config.get('REGISTER_WECHAT') and hasattr(current_app, 'wxauth'):
        ua = request.headers.get('User-Agent', '').lower()
        if 'micromessenger' in ua and '192.168' not in request.host:
            return current_app.wxauth.auth(current_app.wxauth.ACTION_MP, next)

    email_form = um.forms.RegisterEmailForm()
    phone_form = um.forms.RegisterPhoneForm()
    return render_template(
        um.tpls.register,
        next=next, email_form=email_form, phone_form=phone_form
    )


@bp.route('/register/email.html')
def register_email():
    next = request.args.get('next', url_for('users.login'))
    if current_user.is_authenticated():
        return redirect(next)

    token = request.args.get('token')
    code = um.models.EmailCode.get(token)
    if not code:
        return error('该链接已过期')

    form = um.forms.RegisterEmailAccessForm()
    form.email.data = code.email
    form.authcode.data = code.code
    return render_template(
        um.tpls.register_email,
        next=next, code=code, form=form
    )


def login_from_account(next):
    form = um.forms.LoginForm()
    if not um.allow_email or not um.allow_phone:
        form.account.label.text = '帐号'
    return render_template(um.tpls.login, form=form)


@bp.route('/login.html')
def login():
    """ 用户登录 """
    next = request.args.get('next', um.config.login_next or '/')
    if current_user.is_authenticated():
        return redirect(next)

    if next and not next.startswith('http://'):
        next = 'http://%s%s' % (request.host, next)

    if current_app.config.get('WEB_LOGIN_RES_CODE', False):
        return json_error(msg='请登录', login=False)

    if hasattr(current_app, 'ipay'):
        ipay = current_app.ipay
        if ipay.auto_auth:
            return ipay.auth(next)

    if hasattr(current_app, 'wxauth'):
        wxauth = current_app.wxauth
        action = request.args.get('action', '')
        if action == 'account':
            return login_from_account(next)
        if action == 'mp':
            return wxauth.auth(wxauth.ACTION_MP, next)
        if action == 'qrcode':
            return wxauth.auth(wxauth.ACTION_QRCODE, next)

        ua = request.headers.get('User-Agent', '').lower()
        if 'micromessenger' in ua and '192.168' not in request.host \
                and um.config.auto_wxauth:
            return wxauth.auth(wxauth.ACTION_MP, next)

    return login_from_account(next)


@bp.route('/logout.html')
def logout():
    next = request.args.get('next', url_for('users.login'))
    if current_user.is_authenticated():
        logout_user()
    return redirect(next)


@bp.route('/reset_password.html')
def reset_password():
    next = request.args.get('next', url_for('users.login'))
    if current_user.is_authenticated():
        return redirect(next)

    email_form = um.forms.ResetPasswordEmailForm()
    phone_form = um.forms.ResetPasswordPhoneForm()
    return render_template(
        um.tpls.reset_password,
        next=next, email_form=email_form, phone_form=phone_form
    )


@bp.route('/reset_password/email.html')
def reset_password_email():
    next = request.args.get('next', url_for('users.login'))
    if current_user.is_authenticated():
        return redirect(next)

    token = request.args.get('token')
    code = um.models.EmailCode.get(token)
    if not code:
        return error('该链接已过期')

    form = um.forms.ResetPasswordEmailAccessForm()
    form.email.data = code.email
    form.authcode.data = code.code
    return render_template(
        um.tpls.reset_password_email,
        next=next, code=code, form=form
    )


@bp.route('/bind.html')
@login_required
def bind():
    next = request.args.get('next', url_for('users.login'))
    if not um.need_email and not um.need_phone:
        return redirect(next)

    if not current_user.is_user() and current_user.user:
        user = um.models.User.objects(id=current_user.user).first()
        if user:
            login_user(user)
            return redirect(next)
        current_user.user = 0
        current_user.save()

    email_form = um.forms.BindEmailForm()
    phone_form = um.forms.BindPhoneForm()
    return render_template(
        um.tpls.bind, next=next, email_form=email_form, phone_form=phone_form)


@bp.route('/wechat-test.html')
def wechat_test():
    wxuser = um.models.WeChatUser.objects(mp_openid='wechat-test').first()
    if not wxuser:
        wxuser = um.models.WeChatUser(mp_openid='wechat-test')
        wxuser.save()
    wxuser.user = None
    wxuser.save()

    login_user(wxuser)
    next = request.args.get('next', um.config.login_next or '/')
    return redirect(next)

chiki/templates/chiki/users/base.html
{% extends "base.html" %}

{% block body_class %}users{% endblock %}
{% block body %}
<div class="main">
	<div class="{% block main_class %}container{% endblock %}">
		{% block main %}{% endblock %}
	</div>
</div><!-- /.main -->
<div class="footer">
	{% block footer %}{% endblock %}
</div>
{% endblock %}

chiki/templates/chiki/users/login.html
{% extends "users/base.html" %}

{% block subtitle %}用户登录{% endblock %}

{% block main %}
<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
		<div class="box">
			<div class="login">
				<div class="message-box">
					<ul class="nav nav-tabs nav-justified" role="tablist">
					  	<li role="presentation" class="active"><a>用户登录</a></li>
					</ul>
					<div class="message">{{ form | alert }}</div>
				</div>
				<form class="auth-form login-form" action="{{ url_for('users.login') }}" method="post" data-next="{{ next }}">
					{{ form | kform_inline }}
					<button type="submit" class="btn btn-primary btn-lg btn-block">登录</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block footer %}
<div class="text-center links">
	<a href="{{ url_for('users.reset_password') }}">找回密码</a> | 
	<a href="/">首页</a> | 
	<a href="{{ url_for('users.register') }}">注册账号</a>
</div>
{% endblock %}

chiki/templates/chiki/users/register.html
{% extends "users/base.html" %}

{% block subtitle %}用户注册{% endblock %}

{% block main %}
<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
		<div class="box">
			{% if um.allow_email %}
			<div class="register-email" style="display:none">
				<div class="message-box">
					<ul class="nav nav-tabs nav-justified" role="tablist">
					  	<li role="presentation" class="active"><a>使用邮箱注册</a></li>
					</ul>
					<div class="message">{{ email_form | alert }}</div>
				</div>
				<form class="auth-form register-email-form" method="post" data-send="#email" data-next="{{ next }}">
					{{ email_form.csrf_token | kfield_inline }}
					<div class="form-group auth-form-group">
						{{ email_form.email(
							class_="form-control",
							data_label=email_form.email.label.text,
							placeholder=email_form.email.label.text,
							data_empty='true',
							data_regx='^[\w\d]+[\d\w_.]+@([\d\w]+)\.([\d\w]+)(?:\.[\d\w]+)?$',
						) }}
						{% if um.allow_phone %}<a class="use-phone" href="javascript:;">手机注册</a>{% endif %}
					</div>
					<button type="submit" class="btn btn-primary btn-block btn-lg" autocomplete="off">注册</button>
				</form>
				<div class="access"></div>
			</div>
			{% endif %}
			{% if um.allow_phone %}
			<div class="register-phone" style="display:none">
				<div class="message-box">
					<ul class="nav nav-tabs nav-justified" role="tablist">
					  	<li role="presentation" class="active"><a>使用手机号码注册</a></li>
					</ul>
					<div class="message">{{ phone_form | alert }}</div>
				</div>
				<form class="auth-form register-phone-form" method="post" data-send="#phone,.verify-code-box,#verify_code" data-access="#phone,#authcode" data-complete="#phone,#password" data-next="{{ next }}">
					{{ phone_form.csrf_token | kfield_inline }}
					<div class="form-group auth-form-group">
						{{ phone_form.phone(
							class_="form-control",
							data_label=phone_form.phone.label.text,
							placeholder=phone_form.phone.label.text,
							data_empty='true',
							data_regx='^1\d{10}$',
						) }}
						{% if um.allow_email %}<a class="use-email" href="javascript:;">邮箱注册</a>{% endif %}
					</div>
					<div class="verify-code-box">{{ phone_form.verify_code | kfield_inline }}</div>
					<div class="form-group auth-form-group">
						{{ phone_form.authcode(
							class_="form-control",
							data_label=phone_form.authcode.label.text,
							placeholder=phone_form.authcode.label.text,
							data_empty='true',
							style="display:none"
						) }}
						<a class="resend disabled" href="javascript:;" style="display:none">重新发送</a>
					</div>
					{{ phone_form.password | kfield_inline(
						style="display:none", 
						data_empty='true',
						data_min=6,
						data_max=18,
						data_strip='false',
						data_regx='^[\w\d\-\[\]{}|\\,.\/<>;:\'"_`~!@#$%^&*()+= ]+$',
					) }}
					<button type="submit" class="btn btn-primary btn-block btn-lg" autocomplete="off">发送验证码</button>
				</form>
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

{% block footer %}
<div class="text-center links">
	<a href="{{ url_for('users.login') }}">用户登录</a> | 
	<a href="/">首页</a> | 
	<a href="{{ url_for('users.reset_password') }}">找回密码</a>
</div>
{% endblock %}

chiki/templates/chiki/users/register_email.html
{% extends "users/base.html" %}

{% block subtitle %}完成注册{% endblock %}

{% block main %}
<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
		<div class="box">
			<div class="register-email-access">
				<div class="message-box">
					<ul class="nav nav-tabs nav-justified" role="tablist">
					  	<li role="presentation" class="active"><a>邮箱注册</a></li>
					</ul>
					<div class="message">{{ form | alert }}</div>
				</div>
				<form class="auth-form register-email-access-form" method="post" data-complete="#email,#password,#repassword" data-next="{{ next }}">
					{{ form.email | kfield_inline(readonly='readonly') }}
					{{ form.authcode | kfield_inline }}
					{{ form.password | kfield_inline(
						data_empty='true',
						data_min=6,
						data_max=18,
						data_strip='false',
						data_regx='^[\w\d\-\[\]{}|\\,.\/<>;:\'"_`~!@#$%^&*()+= ]+$',
					) }}
					{{ form.repassword | kfield_inline(
						data_strip='false',
						data_empty='true',
						data_equal='#password',
						data_equal_message='两次密码不一致',
					) }}
					<button type="submit" class="btn btn-primary btn-block btn-lg" autocomplete="off">完成注册</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block footer %}
<div class="text-center links">
	<a href="{{ url_for('users.login') }}">用户登录</a> | 
	<a href="/">首页</a> | 
	<a href="{{ url_for('users.register') }}">注册账号</a>
</div>
{% endblock %}

chiki/templates/chiki/users/reset_password.html
{% extends "users/base.html" %}

{% block subtitle %}找回密码{% endblock %}

{% block main %}
<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
		<div class="box">
			{% if um.allow_email %}
			<div class="reset-password-email" style="display:none">
				<div class="message-box">
					<ul class="nav nav-tabs nav-justified" role="tablist">
					  	<li role="presentation" class="active"><a>邮箱找回密码</a></li>
					</ul>
					<div class="message">{{ email_form | alert }}</div>
				</div>
				<form class="auth-form reset-password-email-form" method="post" data-send="#email" data-next="{{ next }}">
					{{ email_form.csrf_token | kfield_inline }}
					<div class="form-group auth-form-group">
						{{ email_form.email(
							class_="form-control",
							data_label=email_form.email.label.text,
							placeholder=email_form.email.label.text,
							data_empty='true',
							data_regx='^[\w\d]+[\d\w_.]+@([\d\w]+)\.([\d\w]+)(?:\.[\d\w]+)?$',
						) }}
					</div>
					<button type="submit" class="btn btn-primary btn-block btn-lg" autocomplete="off">重置密码</button>
					{% if um.allow_phone %}<a class="btn btn-default btn-block btn-lg use-phone" href="javascript:;">短信找回密码</a>{% endif %}
				</form>
				<div class="access"></div>
			</div>
			{% endif %}
			{% if um.allow_phone %}
			<div class="reset-password-phone" style="display:none">
				<div class="message-box">
					<ul class="nav nav-tabs nav-justified" role="tablist">
					  	<li role="presentation" class="active"><a>手机号码找回密码</a></li>
					</ul>
					<div class="message">{{ phone_form | alert }}</div>
				</div>
				<form class="auth-form reset-password-phone-form" method="post" data-send="#phone,.verify-code-box,#verify_code" data-access="#phone,#authcode" data-complete="#phone,#password,#repassword" data-next="{{ next }}">
					{{ phone_form.csrf_token | kfield_inline }}
					<div class="form-group auth-form-group">
						{{ phone_form.phone(
							class_="form-control",
							data_label=phone_form.phone.label.text,
							placeholder=phone_form.phone.label.text,
							data_empty='true',
							data_regx='^1\d{10}$',
						) }}
					</div>
					<div class="verify-code-box">{{ phone_form.verify_code | kfield_inline }}</div>
					<div class="form-group auth-form-group">
						{{ phone_form.authcode(
							class_="form-control",
							data_label=phone_form.authcode.label.text,
							placeholder=phone_form.authcode.label.text,
							data_empty='true',
							style="display:none"
						) }}
						<a class="resend disabled" href="javascript:;" style="display:none">重新发送</a>
					</div>
					{{ phone_form.password | kfield_inline(
						style="display:none",
						data_empty='true',
						data_min=6,
						data_max=18,
						data_strip='false',
						data_regx='^[\w\d\-\[\]{}|\\,.\/<>;:\'"_`~!@#$%^&*()+= ]+$',
					) }}
					{{ phone_form.repassword | kfield_inline(
						data_strip='false',
						data_empty='true',
						data_equal='#password',
						data_equal_message='两次密码不一致',
					) }}
					<button type="submit" class="btn btn-primary btn-lg btn-block" autocomplete="off">发送验证码</button>
					{% if um.allow_email %}<a class="btn btn-default btn-block btn-lg use-email" href="javascript:;">邮件找回密码</a>{% endif %}
				</form>
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

{% block footer %}
<div class="text-center links">
	<a href="{{ url_for('users.login') }}">用户登录</a> | 
	<a href="/">首页</a> | 
	<a href="{{ url_for('users.register') }}">注册账号</a>
</div>
{% endblock %}

chiki/templates/chiki/users/reset_password_email.html
{% extends "users/base.html" %}

{% block subtitle %}设置新密码{% endblock %}

{% block main %}
<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
		<div class="box">
			<div class="reset-password-email-access">
				<div class="message-box">
					<ul class="nav nav-tabs nav-justified" role="tablist">
					  	<li role="presentation" class="active"><a>设置新密码</a></li>
					</ul>
					<div class="message">{{ form | alert }}</div>
				</div>
				<form class="auth-form reset-password-email-access-form" method="post" data-complete="#email,#password,#repassword" data-next="{{ next }}">
					{{ form.email | kfield_inline(readonly='readonly') }}
					{{ form.authcode | kfield_inline }}
					{{ form.password | kfield_inline(
						data_empty='true',
						data_min=6,
						data_max=18,
						data_strip='false',
						data_regx='^[\w\d\-\[\]{}|\\,.\/<>;:\'"_`~!@#$%^&*()+= ]+$',
					) }}
					{{ form.repassword | kfield_inline(
						data_strip='false',
						data_empty='true',
						data_equal='#password',
						data_equal_message='两次密码不一致',
					) }}
					<button type="submit" class="btn btn-primary btn-block btn-lg" autocomplete="off">完成</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block footer %}
<div class="text-center links">
	<a href="{{ url_for('users.login') }}">用户登录</a> | 
	<a href="/">首页</a> | 
	<a href="{{ url_for('users.register') }}">注册账号</a>
</div>
{% endblock %}